### ISSUE TITLE
Table cells with commas in

### ISSUE THREAD

**Issue by peternewman** [gambolputty/wikitable2csv#35]
Trying to parse this:
https://en.wikipedia.org/wiki/Workweek_and_weekend#Around_the_world

It gets tripped up on:
`Congo, Democratic Republic of`

Well it doesn't, but the output isn't any good.

To fix it, you could do one or more of the following:
- Allow alternative delimiters
- Quote the strings

**Comment by gambolputty** [comment]
I rewrote [the app](https://wikitable2csv.ggor.de/). I'm not exactly sure what the issue here was, but the strings were quoted when a quote character or line break was found inside a cell.
I checked the provided URL with [the new version of the app](https://wikitable2csv.ggor.de/) and the table looks fine now. Feel free to reopen, if you think this issue persists.

**Comment by peternewman** [comment]
Thanks @gambolputty . Yeah the new app does indeed seem to correctly handle the comma in a table cell.

> I'm not exactly sure what the issue here was, but the strings were quoted when a quote character or line break was found inside a cell.

Well that would have been the issue, it would also need quoting when the separator character (comma/tab/space or whatever is being used) was found within a cell.

Thanks very much for fixing anyway.

**Comment by gambolputty** [comment]
Yes, you are right! I didn't remember correctly, but the code is handling it the right way
https://github.com/gambolputty/wikitable2csv/blob/faf4399073023ace856c1712ae15f93dde4223fb/src/utils/parseTable.ts#L100-L103

Thanks for reviewing! :)
