### ISSUE TITLE
url not supported

### ISSUE THREAD

**Issue by void285** [gambolputty/wikitable2csv#9]
Hi, I found urls in following format not supported:

> https://zh.wikipedia.org/zh-tw/中国君主列表

For languages which have several styles and will do convertion between each other, this format is normal. So please try to support it, Thanks!

**Comment by gambolputty** [comment]
I just published an update to support other [Wikimedia short urls](https://www.mediawiki.org/wiki/Manual:Short_URL). The issue should be [resolved now](http://wikitable2csv.ggor.de/).

**Comment by rubo77** [comment]
What do you limit the URLs for?

Why not allow any URL there?

**Comment by gambolputty** [comment]
@rubo77 Because this script uses the public Wikimedia API endpoint.

I cannot allow any url, because of [Cross Origin Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin). The script (the Ajax request) would get blocked for security reasons by your browser. For example read [this](https://stackoverflow.com/questions/20035101/why-does-my-javascript-get-a-no-access-control-allow-origin-header-is-present).

**Comment by rubo77** [comment]
and wikipedia is allowing COP?

I would like to use https://wiki.freifunk.net/

**Comment by gambolputty** [comment]
The public API endpoint must allow cross origin access, otherwise it wouldn't be useable as a public API.

Looking at the Freifunk wiki I decided to change the script to allow other top level domains than .ORG to be parsed (all Wikipedias use the .org-TLD, but it doesn't make sense to exclude Wikis hosted on different domains). Do you have an example Freifunk wiki page with a table in it?

**Comment by rubo77** [comment]
https://wiki.freifunk.net/Freifunk_Firmware_Gluon/Hardware

**Comment by gambolputty** [comment]
Unfortunately the Freifunk Wiki (url structure) is badly configured. More specifically: the official Wikimedia docs [recommend NOT to put the Wiki in the root directory](https://www.mediawiki.org/wiki/Manual:Wiki_in_site_root_directory). Normally there is a slug between the host and the Wiki page title, like `https://wiki.freifunk.net/SLUG/Freifunk_Firmware_Gluon/Hardware`.

This is probably why the [API of the Freifunk Wiki](https://wiki.freifunk.net/api.php) is not reachable from the outside via [cross-domain-ajax request](https://wiki.freifunk.net/api.php?action=parse&format=json&origin=*&page=Freifunk_Firmware_Gluon/Hardware&prop=text) (the API must accept an origin parameter of "*"), which is executed by this script.

Anyway, I released a new version with some improvements regarding the url parsing, so other Mediawiki projects should be supported now.
